#!/usr/bin/env node
//
// Generate packages/coding-agent/src/version.generated.ts.
//
// Standalone binaries report the source commit sha from this module (pi -v).
// The sha comes from --sha or PI_SOURCE_SHA (container builds pass the host
// sha as a build arg because .git is excluded from the build context);
// otherwise it falls back to `git rev-parse --short HEAD` on the host and
// finally to "unknown".
//
// The generated file is gitignored; it is regenerated by the coding-agent
// build and by the root `npm run check` before tsgo runs.

import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const repoRoot = resolve(import.meta.dirname, "..");
const outputPath = join(repoRoot, "packages/coding-agent/src/version.generated.ts");

function hostSha() {
	try {
		return execFileSync("git", ["rev-parse", "--short", "HEAD"], {
			cwd: repoRoot,
			encoding: "utf8",
		}).trim();
	} catch {
		return "unknown";
	}
}

const argIndex = process.argv.indexOf("--sha");
const raw = argIndex >= 0 ? process.argv[argIndex + 1] : process.env.PI_SOURCE_SHA || hostSha();
const sha = /^[0-9a-f]+$/i.test(raw) ? raw : "unknown";

writeFileSync(
	outputPath,
	`/* Generated by scripts/generate-version.mjs. Do not edit. */\nexport const SOURCE_SHA = "${sha}";\n`,
);
console.log(`==> generated ${outputPath} (SOURCE_SHA=${sha})`);
